### PR TITLE
chore: prepare for automatic release

### PR DESCRIPTION
**Pull request by sheepduke**
## This PR

* Enforce more strict Clippy rules and fix collisions in existing code.
* Configure build pipeline to pick the rules.
* Add release-please workflow.

### Related Issues

#4

### CODE REVIEW

**Review by toddbaert — APPROVED** [review]
release-plz/CI config looks right to me.

**Comment by sheepduke** [comment]
> release-plz/CI config looks right to me.

Thank you @toddbaert for helping out! How can I configure the CI/CD secrets? 

I definitely do not mind if someone else getting it done...:-)

**Comment by beeme1mr** [comment]
@sheepduke I just finished setting this up with the @openfeaturebot account. I think we're ready to test now!

**Comment by sheepduke** [comment]
> @sheepduke I just finished setting this up with the @openfeaturebot account. I think we're ready to test now!

Great. Let me submit a test PR.

**Pull request merged**
