### PR TITLE
fix: reexport `async_trait::async_trait`

### PR DESCRIPTION
**Pull request by tamaroning**
## This PR
To create a new provider using this library, we need to use the  `#[async_trait]` macro to impl traits.

### Follow-up Tasks

none

### How to test

none

### CODE REVIEW

**Comment by tamaroning** [comment]
Can someone rerun CI?

**Comment by tamaroning** [comment]
Oh thank you. It complained about the title of this pr.

**Comment by beeme1mr** [comment]
> Oh thank you. It complained about the title of this pr.

It should be fixed now.

**Comment by sheepduke** [comment]
Just one question: is it required to export that?

I mean, is it technically required, or does it lead to a better design?
(I thought the user could directly import `async_trait` to achieve this, but it might be ugly...)

**Review by sheepduke — APPROVED** [review]

**Comment by tamaroning** [comment]
I tried to impl FeatureProvider without `#[async_trait]` but couldn't because this macro seems to generate complex lifetime annotations so using the async_trait macro is probabley required.
If this library does not export the macro, users have to import async_trait on their own and make sure that its version matches with this repo. (it will be ugly...)

Async-rust, a famous graphql implementation in Rust, for example, export async_trait in this [line](https://github.com/async-graphql/async-graphql/blob/6a8746304f1f0ec52714bd2eb32fc6e0fedf4f78/src/lib.rs#L225).

**Comment by sheepduke** [comment]
> I tried to impl FeatureProvider without `#[async_trait]` but couldn't because this macro seems to generate complex lifetime annotations so using the async_trait macro is probabley required. If this library does not export the macro, users have to import async_trait on their own and make sure that its version matches with this repo. (it will be ugly)
> 
> Async-rust, a famous graphql implementation in Rust, for example, export async_trait in this [line](https://github.com/async-graphql/async-graphql/blob/6a8746304f1f0ec52714bd2eb32fc6e0fedf4f78/src/lib.rs#L225).

Thanks for your education! Now I totally understand it.

**Pull request merged**
